"""Adiciona herança classe registro

Revision ID: 0fa9a0612507
Revises: c00cee8dbd5e
Create Date: 2025-05-04 11:28:30.149824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0fa9a0612507'
down_revision: Union[str, None] = 'c00cee8dbd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('classificacao', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('processamentos')
    op.drop_table('comercio')
    op.drop_table('producao')
    op.add_column('registros', sa.Column('tipo_operacao', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'registros', 'produtos', ['id_produto'], ['id'])
    op.drop_column('registros', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros', sa.Column('tipo', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'registros', type_='foreignkey')
    op.drop_column('registros', 'tipo_operacao')
    op.create_table('producao',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produto', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('classificacao', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comercio',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produto', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('classificacao', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('processamentos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categoria', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('classificacao', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('produto', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('produtos')
    # ### end Alembic commands ###
