"""Inclusão de Tabelas Produção e Comercialização

Revision ID: 7a8319a08a95
Revises: 3ed539e9e701
Create Date: 2025-05-03 19:01:44.992593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a8319a08a95'
down_revision: Union[str, None] = '3ed539e9e701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('classificacao', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('classificacao', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('processamentos', sa.Column('produto', sa.String(length=30), nullable=False))
    op.drop_column('processamentos', 'cultivo')
    op.add_column('registros', sa.Column('id_produto', sa.Integer(), nullable=False))
    op.drop_constraint('registros_ibfk_1', 'registros', type_='foreignkey')
    op.create_foreign_key(None, 'registros', 'processamentos', ['id_produto'], ['id'])
    op.drop_column('registros', 'id_cultivo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros', sa.Column('id_cultivo', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'registros', type_='foreignkey')
    op.create_foreign_key('registros_ibfk_1', 'registros', 'processamentos', ['id_cultivo'], ['id'])
    op.drop_column('registros', 'id_produto')
    op.add_column('processamentos', sa.Column('cultivo', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('processamentos', 'produto')
    op.drop_table('producao')
    op.drop_table('comercio')
    # ### end Alembic commands ###
