"""Criação inicial das tabelas de processamento 2

Revision ID: a82f567bbc59
Revises: b0aa2b7a072a
Create Date: 2025-04-29 23:48:39.209449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82f567bbc59'
down_revision: Union[str, None] = 'b0aa2b7a072a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cultivo', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('classificacao', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cultivo', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_cultivo'], ['processamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    op.drop_table('processamentos')
    # ### end Alembic commands ###
