"""Adiciona herança classe registro

Revision ID: c00cee8dbd5e
Revises: 7a8319a08a95
Create Date: 2025-05-04 11:05:00.418433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c00cee8dbd5e'
down_revision: Union[str, None] = '7a8319a08a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros', sa.Column('tipo', sa.String(length=20), nullable=False))
    op.drop_constraint('registros_ibfk_1', 'registros', type_='foreignkey')
    op.alter_column('usuarios', 'senha',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'senha',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.create_foreign_key('registros_ibfk_1', 'registros', 'processamentos', ['id_produto'], ['id'])
    op.drop_column('registros', 'tipo')
    # ### end Alembic commands ###
