"""Initial migration

Revision ID: c0854255dc64
Revises: 
Create Date: 2025-05-10 15:42:47.914251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0854255dc64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('control', sa.String(length=100), nullable=False),
    sa.Column('produto', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('classificacao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('registros',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('id_produto', sa.String(length=50), nullable=False),
    sa.Column('tipo_operacao', sa.String(length=20), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    op.drop_table('usuarios')
    op.drop_table('produtos')
    # ### end Alembic commands ###
