"""inclusao do indices

Revision ID: cfe579d127ca
Revises: c1d387864fdc
Create Date: 2025-05-26 22:32:55.348455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe579d127ca'
down_revision: Union[str, None] = 'c1d387864fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_importacao_exportacao_classificacao'), 'importacao_exportacao', ['classificacao'], unique=False)
    op.create_index(op.f('ix_produtos_classificacao'), 'produtos', ['classificacao'], unique=False)
    op.create_index('ix_registros_ano_tipo_operacao', 'registros', ['ano', 'tipo_operacao'], unique=False)
    op.create_index(op.f('ix_registros_id_produto'), 'registros', ['id_produto'], unique=False)
    op.create_index('ix_registros_imp_exp_ano_tipo_operacao', 'registros_importacao_exportacao', ['ano', 'tipo_operacao'], unique=False)
    op.create_index(op.f('ix_registros_importacao_exportacao_id_pais'), 'registros_importacao_exportacao', ['id_pais'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_importacao_exportacao_id_pais'), table_name='registros_importacao_exportacao')
    op.drop_index('ix_registros_imp_exp_ano_tipo_operacao', table_name='registros_importacao_exportacao')
    op.drop_index(op.f('ix_registros_id_produto'), table_name='registros')
    op.drop_index('ix_registros_ano_tipo_operacao', table_name='registros')
    op.drop_index(op.f('ix_produtos_classificacao'), table_name='produtos')
    op.drop_index(op.f('ix_importacao_exportacao_classificacao'), table_name='importacao_exportacao')
    # ### end Alembic commands ###
