"""ajuste de nulidade de campos controle-produto

Revision ID: d3c875955325
Revises: eea7503660cf
Create Date: 2025-05-19 13:29:58.839739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3c875955325'
down_revision: Union[str, None] = 'eea7503660cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produtos', 'control',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('produtos', 'produto',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produtos', 'produto',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('produtos', 'control',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
