"""ajuste dos campos numerico

Revision ID: eea7503660cf
Revises: ae18d197b2f0
Create Date: 2025-05-17 17:31:44.508479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eea7503660cf'
down_revision: Union[str, None] = 'ae18d197b2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('importacao_exportacao', 'quantidade',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=20, scale=0),
               existing_nullable=False)
    op.alter_column('importacao_exportacao', 'valor',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('registros', 'quantidade',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=20, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros', 'quantidade',
               existing_type=sa.Numeric(precision=20, scale=0),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('importacao_exportacao', 'valor',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('importacao_exportacao', 'quantidade',
               existing_type=sa.Numeric(precision=20, scale=0),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
