"""inclusao do campo source id

Revision ID: fba3994ad31b
Revises: b50e4ef3db1b
Create Date: 2025-05-17 12:14:39.198841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba3994ad31b'
down_revision: Union[str, None] = 'b50e4ef3db1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('source_id', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'source_id')
    # ### end Alembic commands ###
